### ISSUE TITLE
Library Class

### ISSUE THREAD

**Issue by tyom29** [Elen-2204/Library_management_system#1]
Elen jan, I would greatly appreciate it if you could separate the library functionality. I highly recommend creating a "Library" class and consolidating all library-related functionalities within that class. This approach will enhance your  project's organization, maintainability and scalability.

**Comment by Elen-2204** [comment]
[heart]         Elen Grigoryan reacted to your message:
________________________________
From: Artyom Yeprikyan ***@***.***>
Sent: Sunday, February 18, 2024 7:01:28 PM
To: Elen-2204/Library_management_system ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Elen-2204/Library_management_system] Library Class (Issue #1)


Elen jan, I would greatly appreciate it if you could separate the library functionality. I highly recommend creating a "Library" class and consolidating all library-related functionalities within that class. This approach will enhance your project's organization, maintainability and scalability.
